#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/wild_encounters.json and Inja template src/data/wild_encounters.constants.json.txt
//


#define NUM_ALTERING_CAVE_TABLES 9

#define NUM_LAND_MONS_ENCOUNTER_SLOTS (12)

#define NUM_WATER_MONS_ENCOUNTER_SLOTS (5)

#define NUM_ROCK_SMASH_MONS_ENCOUNTER_SLOTS (5)


#define NUM_FISHING_MONS_GOOD_ROD_ENCOUNTER_SLOTS (3)

#define NUM_FISHING_MONS_OLD_ROD_ENCOUNTER_SLOTS (2)

#define NUM_FISHING_MONS_SUPER_ROD_ENCOUNTER_SLOTS (5)
#define NUM_FISHING_MONS_ENCOUNTER_SLOTS (10)


#define NUM_HIDDEN_MONS_ENCOUNTER_SLOTS   3

#define WILD_CHECK_REPEL    (1 << 0)
#define WILD_CHECK_KEEN_EYE (1 << 1)

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
